name = "wskv-test"
main = "src/test/worker.ts"
compatibility_date = "2026-02-09"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WSKV_TEST"
class_name = "WskvTestDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WskvTestDO"]
